# Generated by Django 5.1.5 on 2026-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
